title: Jon Hadley
copyright: Jonathan Hadley
description: Senior Delivery Leader, Technology & AI
url: "https://jon-hadley.com"
google_analytics: UA-49873606-1
show_downloads: true
remote_theme: "mmistakes/minimal-mistakes@4.28.0"
minimal_mistakes_skin: default

footer:
  since: 1997

atom_feed:
  hide: true

author:
  name: Jon Hadley
  avatar: "/assets/images/me-colour-small.jpg"
  location: Bristol, UK
  bio: Senior Delivery Leader,<br>Technology & AI
  links:
    - label: Instagram
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/mint5auce/"
    - label: LinkedIn
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jonhadley"
    - label: GitHub
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mint5auce"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-mentions

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - mise.toml
  - vendor
